### ISSUE TITLE
Intention of CHA-RL5b is not clear

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/specification#223]
> ** @(CHA-RL5b)@ @[Testable]@ If the operation above fails (i.e. the call to the @CHA-RL2f@ detach procedure fails), room status is still @SUSPENDED@, then it must be retried after a short wait of 250ms.

The CHA-RL2f detachment cycle already describes a retry mechanism (CHA-RL2h3). This makes me wonder whether CHA-RL5b is actually describing a new behaviour, or whether it’s just a leftover from before RETRY was written in terms of the CHA-RL2f detachment cycle? (It’s not even clear to me whether the situation described in CHA-RL5b can ever occur; doesn’t the CHA-RL2f deatch procedure either succeed or transition to FAILED?)

**Comment by AndyTWF** [comment]
Yeah I think we can just point at CHA-RL2f, as that provides the required behaviour :)
