### ISSUE TITLE
Chat spec points about preventing presence are unclear

### ISSUE THREAD

**Issue by lawrence-forooghian** [ably/specification#236]
I am not sure I understand the meaning of spec points CHA-PR9a and CHA-PR9b, which describe how the room’s presence options affect the channel modes that are used when attaching.

- The spec points are written in the form of "if this option is false, then take this action", but the implementation in JS (which it looks like we’ve copied in Swift) seems to [do the opposite](https://github.com/ably/ably-chat-js/blob/533c4d0314bcce942a30b4d7d6a012c3b081420d/src/core/presence.ts#L221-L227); that is, if the option is true then it sets a given channel option.
- I don't really understand what it means to "prevents the user from (doing something) by means of the `ChannelMode` on the underlying realtime channel"; could we write this in a more prescriptive form as "if this option (is or isn't) set, then set flag $x$ when attaching to the channel"?

**Comment by AndyTWF** [comment]
Agree with what you've mentioned - opened a PR to reword :)
