### ISSUE TITLE
Add mandatory `version` parameter to `rest#request`

### ISSUE THREAD

**Issue by QuintinWillison** [ably/specification#7]
This change was originally proposed by @SimonWoolf in https://github.com/ably/docs/pull/1592.

The features spec moved to this repository before that proposed change was approved or merged, therefore this issue represents the requirement to create a pull request in this repository for that change.

To assist, I have already pushed up a branch with commit co-authored-by Simon containing the same change to save time:

- From `compare`: [branch `rest-request-with-version`](https://github.com/ably/specification/tree/rest-request-with-version)
- To `base`: [branch `integration/protocol-2.0`](https://github.com/ably/specification/tree/integration/protocol-2.0)

👉 [**Compare & pull request**](https://github.com/ably/specification/compare/integration/protocol-2.0...rest-request-with-version?expand=1)

**Comment by SimonWoolf** [comment]
PR: https://github.com/ably/specification/pull/89
