### ISSUE TITLE
Protocol v2.0: no-connection-serial

### ISSUE THREAD

**Issue by QuintinWillison** [ably/specification#8]
This change was originally proposed by @SimonWoolf in https://github.com/ably/docs/pull/1526.

The features spec moved to this repository before that proposed change was approved or merged, therefore this issue represents the requirement to create a pull request in this repository for that change.

To assist, I have already pushed up a branch with commit co-authored-by Simon containing the same change to save time:

- From `compare`: [branch `no-connection-serial`](https://github.com/ably/specification/tree/no-connection-serial)
- To `base`: [branch `integration/protocol-2.0`](https://github.com/ably/specification/tree/integration/protocol-2.0)

👉 [**Compare & pull request**](https://github.com/ably/specification/compare/integration/protocol-2.0...no-connection-serial?expand=1)

**Comment by SimonWoolf** [comment]
PR opened: https://github.com/ably/specification/pull/88
